// Immediately Invoked Function Expressions (IIFE)
// REASON : GLOBAL SCOPE SE POLLUTION NO JOTVU HOY TAYRE AND IMMEDIATLY EXCUTE THAY ATLE 
// IN SIMPLE TERM : JAYRE GLOBAL SCOPE MA KOY VARIABLE DECLARE KARYU ANE TE FXN MA PAN HOY TO TE GLOBAL VARIABLE KAY PROBLEM(KARAN KE TE LOCAL TO GLOBAL PASE THI MANGI SAKE) KARE TETHI FXN immediatly excute thay jay



(function chai(){
    //NAMED IIFE
    console.log(`DB CONNECTED`);
})();
  
// ; 2 IIFE NI VACHE MUKVANU NO BHULAY NAHITAR ERROR AVSHE

((name) => {
    console.log(`DB CONNECTED TWO ${name}`);
}
)("harshil")

